In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import keras
import keras.preprocessing.image
from keras_retinanet.models.resnet import custom_objects
from keras_retinanet.preprocessing.coco import CocoGenerator

import matplotlib.pyplot as plt
import cv2
import os
import numpy as np
import time

import tensorflow as tf

def get_session():
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    return tf.Session(config=config)

# os.environ["CUDA_VISIBLE_DEVICES"] = "0"
keras.backend.tensorflow_backend.set_session(get_session())

Using TensorFlow backend.


## Load RetinaNet model

In [2]:
model = keras.models.load_model('D:\Luis\codigos\snapshot/resnet50_pascal_50.h5', custom_objects=custom_objects)
#print(model.summary())

c:\users\luis\anaconda3\envs\keras_tf35_gpu\lib\site-packages\keras\models.py:252: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


## Initialize data generators

In [4]:
# create image data generator object
val_image_data_generator = keras.preprocessing.image.ImageDataGenerator()

# create a generator for testing data
val_generator = CocoGenerator(
    'D:\Luis\codigos\deep learning\basketball\ImageSets\Main',
    'val',
    val_image_data_generator,
    batch_size=1,
)
index = 0

loading annotations into memory...


OSError: [Errno 22] Invalid argument: 'D:\\Luis\\codigos\\deep learning\x08asketball\\ImageSets\\Main\\annotations\\instances_val.json'

In [5]:
import cv2


In [121]:
image = cv2.imread("D:\\Luis\\codigos\\deep learning\\basketball\\JPEGImages\\n02802426_9097.jpeg")
print(image.shape)

(375, 500, 3)


In [122]:
draw = image.copy()
draw = cv2.cvtColor(draw, cv2.COLOR_BGR2RGB)



In [123]:
_, _, detections = model.predict_on_batch(np.expand_dims(image, axis=0))

In [124]:
detections

array([[[  5.28039627e+01,   1.61403580e+02,   9.37964401e+01,
           2.03849411e+02,   6.28129900e-01],
        [  6.34011917e+01,   1.72393005e+02,   1.05770790e+02,
           2.10625366e+02,   1.22438893e-01],
        [  4.51224747e+01,   1.73276382e+02,   8.41555557e+01,
           2.15092667e+02,   1.08145602e-01],
        ..., 
        [  2.60218567e+02,   3.54939972e+02,   2.91618652e+02,
           3.86901398e+02,   1.00687868e-03],
        [  3.74542694e+02,   9.82149811e+01,   5.48493530e+02,
           1.92362106e+02,   1.00192474e-03],
        [ -1.62191124e+01,   2.24748993e+02,   2.69208107e+01,
           2.47344421e+02,   9.98640200e-04]]], dtype=float32)

In [125]:
predicted_labels = np.argmax(detections[0, :, 4:], axis=1)


In [126]:
predicted_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0], d

In [127]:
scores = detections[0, np.arange(detections.shape[1]), 4 + predicted_labels]


In [128]:
# scores

In [129]:
idx=0
# if score < 0.5:
#     continue
b = detections[0, idx, :4].astype(int)
cv2.rectangle(draw, (b[0], b[1]), (b[2], b[3]), (0, 0, 255), 3)
# caption = "{} {:.3f}".format(val_generator.label_to_name(label), score)
caption = "ball"
cv2.putText(draw, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1.5, (0, 0, 0), 3)
cv2.putText(draw, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1.5, (255, 255, 255), 2)
    

array([[[128, 134, 134],
        [124, 129, 133],
        [129, 133, 132],
        ..., 
        [134, 138, 139],
        [134, 138, 137],
        [136, 140, 139]],

       [[122, 126, 138],
        [126, 130, 142],
        [129, 132, 149],
        ..., 
        [140, 135, 139],
        [140, 137, 132],
        [143, 141, 129]],

       [[125, 130, 136],
        [127, 135, 124],
        [126, 135, 134],
        ..., 
        [134, 133, 149],
        [136, 133, 150],
        [140, 138, 152]],

       ..., 
       [[ 88,  52,  18],
        [ 80,  50,  16],
        [ 77,  47,   9],
        ..., 
        [127,  95,  57],
        [127,  96,  49],
        [126,  94,  55]],

       [[ 75,  50,  46],
        [ 70,  51,  45],
        [ 68,  46,  33],
        ..., 
        [126,  98,  48],
        [122,  97,  33],
        [123,  92,  45]],

       [[ 54,  40,  31],
        [ 64,  48,  33],
        [ 76,  56,  23],
        ..., 
        [127,  97,  71],
        [124, 103,  12],
        [127,  97,

In [130]:
cv2.imshow("prueba", draw)
cv2.waitKey()
cv2.destroyAllWindows()

## Run detection on example

In [9]:
# load image
# image = val_generator.load_image(index)
image = cv2.imread("D:\\Luis\\codigos\\deep learning\\basketball\\JPEGImages\\n02802426_227.jpeg")
# copy to draw on
draw = image.copy()
draw = cv2.cvtColor(draw, cv2.COLOR_BGR2RGB)

# preprocess image for network
image = val_generator.preprocess_image(image)
image, scale = val_generator.resize_image(image)
annotations = val_generator.load_annotations(index)
index += 1

# process image
start = time.time()
_, _, detections = model.predict_on_batch(np.expand_dims(image, axis=0))
print("processing time: ", time.time() - start)

# compute predicted labels and scores
predicted_labels = np.argmax(detections[0, :, 4:], axis=1)
scores = detections[0, np.arange(detections.shape[1]), 4 + predicted_labels]

# correct for image scale
detections[0, :, :4] /= scale

# visualize detections
for idx, (label, score) in enumerate(zip(predicted_labels, scores)):
    if score < 0.5:
        continue
    b = detections[0, idx, :4].astype(int)
    cv2.rectangle(draw, (b[0], b[1]), (b[2], b[3]), (0, 0, 255), 3)
    caption = "{} {:.3f}".format(val_generator.label_to_name(label), score)
    cv2.putText(draw, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1.5, (0, 0, 0), 3)
    cv2.putText(draw, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1.5, (255, 255, 255), 2)
    
# visualize annotations
for annotation in annotations:
    label = int(annotation[4])
    b = annotation[:4].astype(int)
    cv2.rectangle(draw, (b[0], b[1]), (b[2], b[3]), (0, 255, 0), 2)
    caption = "{}".format(val_generator.label_to_name(label))
    cv2.putText(draw, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1.5, (0, 0, 0), 3)
    cv2.putText(draw, caption, (b[0], b[1] - 10), cv2.FONT_HERSHEY_PLAIN, 1.5, (255, 255, 255), 2)
    
plt.figure(figsize=(15, 15))
plt.axis('off')
plt.imshow(draw)
plt.show()

NameError: name 'val_generator' is not defined